RealEstate.Web/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RealEstate.Web.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage="Email is required")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$",ErrorMessage="Invalid email format")]
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
    }
}

RealEstate.Web/Models/EnquiryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RealEstate.Web.Models
{
    
    public class EnquiryViewModel
    {
        public int CommentId { get; set; }

        [Display(Name="First Name")]
        [Required(ErrorMessage="Firstname is required")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Lastname is required")]
        public string LastName { get; set; }
        
        [Required(ErrorMessage = "Email is required")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Invalid email format")]
        public string Email { get; set; }

        [Display(Name = "Phone Numebr")]
        [Required(ErrorMessage = "Phone is required")]
        public string Phone { get; set; }

        [Display(Name = "Comment")]
        [Required(ErrorMessage = "Comment is required")]
        public string Comment { get; set; }
    }
}

RealEstate.Web/Models/JsonResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RealEstate.Web.Models
{
    public class JsonResponseModel
    {
        public JsonResponseModel(bool sucess,string message = null)
        {
            this.Success = sucess;
            this.Message = message;
            this.Errors = new List<string>();
        }
        public bool Success { get; set; }
        public string Message { get; set; }
        public List<string> Errors { get; set; }
    }
}

RealEstate.Web/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RealEstate.Web.Models
{
    public class RegisterViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}

RealEstate.Web/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RealEstate.Web.Models
{
    public class UserViewModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }        
        public string Password { get; set; }
    }
}

RealEstate.Web/Controllers/AccountController.cs
using RealEstate.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.Web.Controllers
{
    public class AccountController : Controller
    {        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Contact(ContactViewModel contact)
        {
            return Json("An email has been sent.Someone will get contact you in the following days");
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(RegisterViewModel register)
        {
            return Json("An email has been sent.Someone will get contact you in the following days");
        }

    }
}

RealEstate.Web/Controllers/EnquiryController.cs
using RealEstate.BLL;
using RealEstate.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RealEstate.Web.Extensions;

namespace RealEstate.Web.Controllers
{
    public class EnquiryController : Controller
    {
        public AccountLogic AccountBLL
        {
            get { return new AccountLogic(); }
        }
        
        public ActionResult Add()
        {
            EnquiryViewModel model = new EnquiryViewModel();
            return View("Add", model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(EnquiryViewModel vm)
        {
            await AccountBLL.RealEstateEnquiryCreate(vm.ToPoco());
            return Json(new JsonResponseModel(true, "Thank You for your interest ,one of our agents will contact you within two days"));
        }
    }
}

RealEstate.Web/Views/Enquiry/Add.cshtml
@model RealEstate.Web.Models.EnquiryViewModel

@{
    ViewBag.Title = "Add Enquiry";
}

<h3>@ViewBag.Title</h3>

@using (Html.BeginForm("Add", "Enquiry", FormMethod.Post, new { data_abide = ""}))
{
    <div class="row">
        <div class="small-6 columns">
            @Html.LabelFor(m => m.FirstName)
            @Html.TextBoxFor(m => m.FirstName, new { @class = "first_name", required = "required" })
        </div>
        <div class="small-6 columns">
            @Html.LabelFor(m => m.LastName)
            @Html.TextBoxFor(m => m.LastName, new { @class = "last_name", required = "required" })
        </div>
    </div>
    <div class="row">
        <div class="small-6 columns">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "email",  required = "required",pattern=@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$" })
        </div>
        <div class="small-6 columns">
            @Html.LabelFor(m => m.Phone)
            @Html.TextBoxFor(m => m.Phone, new { @class = "phone" , required = "required"})
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            @Html.LabelFor(m => m.Comment)
            @Html.TextAreaFor(m => m.Comment, new { @class = "realestate-comment", required = "required" })
        </div>
    </div>
   
    <div class="row">
        <div class="small-3 right columns">
            <input type="submit" class="button" value="Add Comment" />
            <input type="submit" class="button" value="Cancel" />
        </div>
    </div>
    

}

RealEstate.Web/Views/Enquiry/Enquiry.cshtml
@model RealEstate.Web.Models.EnquiryViewModel

@{
    ViewBag.Title = "Create Enquiry";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Enquiry", "Enquiry", FormMethod.Post, new { data_abide = " " }))
{
    <div class="row">
        <div class="small-3 columns">
            @Html.LabelFor(m => m.FirstName)
            @Html.TextBoxFor(m => m.FirstName, new { @class="first_name"})
        </div>
        <div class="small-3 columns">
            @Html.LabelFor(m => m.LastName)
            @Html.TextBoxFor(m => m.LastName, new { @class = "last_name" })
        </div>
        <div class="small-3 columns">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "email" })
        </div>
        <div class="small-3 columns">
            @Html.LabelFor(m => m.Phone)
            @Html.TextBoxFor(m => m.Phone, new { @class = "phone" })
        </div>
        
    </div>
    <div class="row">
        <div class="small-12 columns">
            @Html.LabelFor(m => m.Comment)
            @Html.TextAreaFor(m => m.Comment,new{@class="realestate-comment"})
        </div>
    </div>
   
    <div class="row">
        <div class="small-3 right columns">
            <input type="submit" class="button" value="Add Comment" />
            <input type="submit" class="button" value="Cancel" />
        </div>
    </div>
    

}

RealEstate.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

@{
    
    ViewBag.Title = "TBD";
}
<body>
    <div class="top-bar">
        <div class="top-bar-left">            
            <ul class="dropdown menu" data-dropdown-menu>
                <li class="menu-text">@ViewBag.Title</li>
                <li>
                    <a href="#">One</a>
                    <ul class="menu vertical">
                        <li><a href="#">One</a></li>
                        <li><a href="#">Two</a></li>
                        <li><a href="#">Three</a></li>
                    </ul>
                </li>
                <li><a href="#">Two</a></li>
                <li><a href="#">Three</a></li>
            </ul>            
        </div>
        <div class="top-bar-right">
            <ul class="menu">                
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @*<li><input type="search" placeholder="Search"></li>
                <li><button type="button" class="button">Search</button></li>*@
            </ul>
        </div>
    </div>
    @RenderBody()
    <footer class="row">
        <hr/>
        <div class="large-12 columns">           

            <div class="row">
                <div class="large-6 columns">
                    <p>Content</p>
                </div>


                <div class="large-6 columns">
                    <p>Content</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/foundation") 
    <script>
        $(document).foundation();
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>